<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>

<body>
    <script>
        /* membuat validation error manual */
        class ValidationError extends Error {

            constructor(message, field) {
                super(message)
                this.field = field
            }
        }

        class MathUtill {

            static sum(...numbers) {

                if (numbers.length == 0) {
                    throw new ValidationError('parameter harus lebih dari 0', 'numbers')
                }

                let total = 0
                for (const number of numbers) {
                    total += number
                }
                return total
            }
        }
        const result = MathUtill.sum(5, 5, 5, 4, 1)
        console.info(`hasil ${result}`);


        /* try catch */
        try {
            console.info(MathUtill.sum());
            console.info('kode block try akan terhenti, catch tidak akan di eksekusi')
        } catch (error) {

            if (error instanceof ValidationError) {
                console.error(`Terjadi error pada field ${error.field} dengan error : ${error.message}`);
            } else {
                console.error(`Terjadi error : ${error.message}`);
            }
        }
        console.info('memakai try catch kode program dibawahnya tidak akan terhenti');
    </script>
</body>

</html>